#!/bin/sh
SERVICE=aux_store
DEPLOY_DIR=/kb/deployment
SERVICE_DIR=$DEPLOY_DIR/services/$SERVICE

echo stopping uploader
if [ ! -f $SERVICE_DIR/uploader.pid ]; then
   echo "No pid file $SERVICE_DIR/uploader.pid found for service uploader" 1>&2
   exit 1
fi

PID=`cat $SERVICE_DIR/uploader.pid`
kill $PID
rm $SERVICE_DIR/uploader.pid

echo stopping aux_store services
pid_file=$SERVICE_DIR/aux_store.pid
if [ ! -f $pid_file ] ; then 
	echo "No pid file: $pid_file found for service aux_store."
	exit 1
fi
pid=$(cat $pid_file)
kill $pid
rm $pid_file
echo done
  
