#!/bin/sh
DEPLOY=/kb/deployment
SERVICE=$DEPLOY/services/aux_store

echo stopping aux_store services
pid_file=$SERVICE/aux_store.pid
if [ ! -f $pid_file ] ; then 
	echo "No pid file: $pid_file found for service aux_store."
	exit 1
fi
pid=$(cat $pid_file)
kill $pid
rm $pid_file
echo done
  