#!/bin/sh

rm -rf	lib/AbstractHandleImpl.py.bak-2014*
rm -rf	lib/AbstractHandleServer.py
rm -rf	lib/Bio/KBase/AbstractHandle/AbstractHandleImpl.pm.bak-2014*
rm -rf	lib/Bio/KBase/AbstractHandle/Client.pm
rm -rf	lib/Bio/KBase/AbstractHandle/Service.pm
rm -rf	lib/biokbase/
rm -rf	lib/javascript/
rm -rf	pod2htmd.tmp
rm -rf	docs/AbstractHandle.html
rm -rf	lib/AbstractHandle.psgi
rm -rf	lib/AbstractHandleImpl.py
rm -rf  service/AbstractHandle.conf

