#!/bin/sh

day=$1
rm -rf	lib/AbstractHandleImpl.py.bak-2013-10-$day*
rm -rf	lib/AbstractHandleServer.py
rm -rf	lib/Bio/KBase/AbstractHandle/AbstractHandleImpl.pm.bak-2013-10-$day*
rm -rf	lib/Bio/KBase/AbstractHandle/Client.pm
rm -rf	lib/Bio/KBase/AbstractHandle/Service.pm
rm -rf	lib/biokbase/
rm -rf	lib/javascript/
rm -rf	pod2htmd.tmp

